services:
    # Command
    Smart\CoreBundle\Command\CommandPoolHelper:
        arguments:
            - '@Symfony\Component\HttpKernel\KernelInterface'
            - '@translator'
    # Config
    Smart\CoreBundle\Config\IniOverrideConfig:
        arguments:
            - '%env(default::SMART_CORE_BATCH_MEMORY)%'
    # Controller
    Smart\CoreBundle\Controller\MonitoringController:
        calls:
            -   setContainer: [ '@service_container' ]
            -   setEntityManager: [ '@Doctrine\ORM\EntityManagerInterface' ]
        tags: [ 'controller.service_arguments' ]
    # Monitoring
    Smart\CoreBundle\Monitoring\ApiCallMonitor:
        arguments:
            - '@Smart\CoreBundle\Monitoring\ProcessMonitor'
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
    Smart\CoreBundle\Monitoring\ProcessMonitor:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
    # Route
    Smart\CoreBundle\Route\RouteLoader:
        tags:
            - { name: routing.loader }
    # Sentry
    Smart\CoreBundle\Sentry\SentryCallback:
    # Alice
    # Service Fidry\AliceDataFixtures\Loader\PurgerLoader not exist, and it must be aliased. AbstractFixtures need it.
    Fidry\AliceDataFixtures\Loader\PurgerLoader: '@fidry_alice_data_fixtures.doctrine.purger_loader'
