name: Coverage and QA

on: [ pull_request ]

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [
                    # '8.2', Not supported due to SYMFONY_PHPUNIT_VERSION set 12.2 requiring php 8.3
                    '8.3',
                    '8.4'
                ]
                orm: ['2.19.*', '^3.0'] # must be working on both
        container:
            image: ghcr.io/${{ github.repository_owner }}/symfony-docker:php${{ matrix.php }}
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Configure GitHub token for Composer
                run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
            # Dynamically update composer.json dependencies before running make install
            -   name: "Restrict Doctrine ORM version"
                run: composer require "doctrine/orm:${{ matrix.orm }}" --no-update --no-interaction
            -   name: "Install: vendor & clear cache"
                run: make install
            -   name: Run coverage
                run: make coverage
            -   name: Run qualimetry
                run: make qualimetry
