name: Coverage and QA

on: [ pull_request ]

jobs:
    ci:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/${{ github.repository_owner }}/symfony-docker:php8.4
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Configure GitHub token for Composer
                run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
            -   name: "Install: vendor & clear cache"
                run: make install
            -   name: Run coverage
                run: make coverage
            -   name: Run qualimetry
                run: make qualimetry
